#!/usr/bin/env node
// Build the self-contained binaries.
//
//   bun packaging/binary/build.mjs                 # native target -> dist/binaries/
//   bun packaging/binary/build.mjs --target darwin-arm64
//   bun packaging/binary/build.mjs --all           # all four release targets
//
// Requires `bun run build:web` first: dist/web is embedded into the binary.
// macOS binaries are ad-hoc signed (with JIT entitlements) and verified. The
// tap's formula installs these binaries, so no notarization is needed.
import { spawnSync } from "node:child_process";
import { access, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../..");
const webDir = resolve(repoRoot, "dist/web");
const generatedDir = resolve(repoRoot, "dist/binary");
const generatedAssets = join(generatedDir, "web-assets.ts");
const outDir = resolve(repoRoot, "dist/binaries");

const TARGETS = {
  "darwin-arm64": "bun-darwin-arm64",
  "darwin-x64": "bun-darwin-x64",
  "linux-x64": "bun-linux-x64",
  "linux-arm64": "bun-linux-arm64",
};

function parseArgs(argv) {
  let all = false;
  let target;
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === "--all") {
      all = true;
    } else if (argv[i] === "--target") {
      target = argv[(i += 1)];
    }
  }
  if (all && target) {
    throw new Error("use either --all or --target, not both");
  }
  if (target && !(target in TARGETS)) {
    throw new Error(
      `unknown target "${target}"; expected one of ${Object.keys(TARGETS).join(", ")}`,
    );
  }
  return { all, target };
}

function nativePlatform() {
  const arch = process.arch === "arm64" ? "arm64" : "x64";
  return `${process.platform}-${arch}`;
}

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walk(full)));
    } else if (entry.isFile()) {
      files.push(full);
    }
  }
  return files;
}

async function generateAssetModule() {
  const files = (await walk(webDir)).sort();
  const imports = [];
  const mappings = [];
  files.forEach((file, index) => {
    const relativePath = relative(webDir, file).split(sep).join("/");
    const specifier = relative(generatedDir, file).split(sep).join("/");
    imports.push(`import asset${index} from ${JSON.stringify(specifier)} with { type: "file" };`);
    mappings.push(`  ${JSON.stringify(relativePath)}: asset${index},`);
  });
  const source = [
    "// Generated by packaging/binary/build.mjs. Do not edit.",
    ...imports,
    "",
    "export const webAssets: Record<string, string> = {",
    ...mappings,
    "};",
    "",
  ].join("\n");
  await mkdir(generatedDir, { recursive: true });
  await writeFile(generatedAssets, source);
}

function run(command, args) {
  const result = spawnSync(command, args, { cwd: repoRoot, stdio: "inherit" });
  if (result.error) {
    throw result.error;
  }
  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} exited with ${result.status}`);
  }
}

function compile(platform, version) {
  const outfile = join(outDir, `structurizr-site-${platform}`);
  run("bun", [
    "build",
    join(here, "entry.ts"),
    "--compile",
    `--target=${TARGETS[platform]}`,
    "--outfile",
    outfile,
    "--define",
    `__STRUCTURIZR_SITE_VERSION__=${JSON.stringify(version)}`,
  ]);
  if (platform.startsWith("darwin-")) {
    signMac(outfile);
  }
  return outfile;
}

function signMac(outfile) {
  run("codesign", [
    "--force",
    "--sign",
    "-",
    "--entitlements",
    join(here, "entitlements.plist"),
    outfile,
  ]);
  run("codesign", ["--verify", "--strict", outfile]);
}

async function main() {
  const { all, target } = parseArgs(process.argv.slice(2));

  if (!(await exists(webDir))) {
    throw new Error(`prebuilt web app not found at ${webDir}; run "bun run build:web" first`);
  }

  const pkg = JSON.parse(await readFile(resolve(repoRoot, "package.json"), "utf8"));
  await mkdir(outDir, { recursive: true });
  await generateAssetModule();

  const platforms = all ? Object.keys(TARGETS) : [target ?? nativePlatform()];
  if (!all && !(platforms[0] in TARGETS)) {
    throw new Error(`unsupported native platform "${platforms[0]}"; pass --target explicitly`);
  }

  for (const platform of platforms) {
    const outfile = compile(platform, pkg.version);
    console.log(`Built ${outfile}`);
  }
}

async function exists(path) {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

await main();
